export const pythonEnglish = {
  'python-syntax-for-js': {
    title: 'Python syntax for a JavaScript developer',
    eyebrow: 'Read Python without guessing',
    summary: 'Learn the minimum syntax, collections, control flow, functions, and module rules needed to read everyday Python code.',
    theory: 'Python uses indentation as grammar, binds names to objects dynamically, iterates over iterable values directly, and expresses many transformations through comprehensions. Similar-looking JavaScript constructs often have different contracts.',
    watchFor: 'The live CPython process creates real lists and dictionaries, filters with a comprehension, unpacks a sequence, uses enumerate, and calls a function with a keyword-only argument.',
    expected: [
      'Top-level statements execute in source order.',
      'Names point to objects rather than fixed-type variable slots.',
      'A comprehension combines transformation, iteration, and filtering.',
      'Sequence unpacking binds several names in one statement.',
      'Type annotations do not perform runtime validation by themselves.',
    ],
    code: 'orders = [\n    {"id": "A-10", "status": "paid", "price": 120},\n    {"id": "A-11", "status": "draft", "price": 80},\n]\n\npaid_ids = [\n    order["id"]\n    for order in orders\n    if order["status"] == "paid"\n]\n\ndef describe(order, *, currency="RUB"):\n    return f"{order[\'id\']} · {order[\'price\']} {currency}"',
    learning: {
      plain: 'Python is not merely JavaScript without braces. Indentation defines blocks, names refer to objects, collections have different guarantees, and direct iterable traversal replaces many index-based loops. This chapter aims to make an unfamiliar file readable before you can write a library yourself.',
      foundation: 'A .py file consists of statements and expressions. Assignment binds a name to an object rather than declaring a fixed-type storage cell. A colon starts a suite whose extent is defined by indentation. def creates a function object, import executes and caches a module, and for requests items from an iterable.',
      why: 'False analogies are the main risk for a JS developer: dict resembles object but is a mapping; list resembles Array but slicing and comprehensions change common patterns; None is not undefined; and is tests identity rather than value.',
      codeLanguage: 'Python',
      snippetLabel: 'src/python-lab.py · educational snippet',
      runtimeCodeHint: 'The first file is the real CPython scenario; the second safely starts the child process and turns its JSON Lines into the live trace.',
      runtimeTraceConnection: 'Python calls emit(...) and prints JSON Lines to stdout. The Node bridge reads them without a shell, bounds runtime and output, and forwards events into the HTTP stream.',
      resources: [
        { label: 'The Python Tutorial', description: 'The official route through syntax, collections, modules, errors, and classes.', href: 'https://docs.python.org/3/tutorial/' },
        { label: 'Built-in Types', description: 'Precise list, tuple, dict, set, string, and truth-testing behavior.', href: 'https://docs.python.org/3/library/stdtypes.html' },
        { label: 'Control Flow', description: 'if, for, range, match, def, parameters, and argument unpacking.', href: 'https://docs.python.org/3/tutorial/controlflow.html' },
      ],
      runtimeLayers: [
        { title: 'PYTHON SOURCE', detail: '.py · statements · expressions', active: true },
        { title: 'PARSER', detail: 'tokens · AST · scopes' },
        { title: 'CPYTHON', detail: 'code objects · bytecode · frames' },
        { title: 'OBJECTS', detail: 'types · collections · stdlib' },
      ],
      terms: [
        ['Name', 'An identifier bound to an object. Reassignment changes the binding rather than the type of a dedicated variable cell.'],
        ['Statement', 'An instruction such as if, for, import, return, or assignment that controls execution.'],
        ['Expression', 'A fragment evaluated into an object value, such as a call, arithmetic expression, comprehension, or subscription.'],
        ['Iterable', 'An object whose items can be requested one by one by for, a comprehension, sum, list, and other consumers.'],
        ['list', 'A mutable ordered sequence. It resembles a JS Array, but its methods and copy model differ.'],
        ['tuple', 'An immutable sequence commonly used for a fixed group of values and unpacking.'],
        ['dict', 'A key-to-value mapping. Keys must be hashable; [] raises KeyError for a missing key while get returns a fallback.'],
        ['set', 'A collection of unique hashable items with fast membership tests and set operations.'],
        ['None', 'The singleton object representing no value, normally compared with is None.'],
        ['Comprehension', 'An expression that builds a list, dictionary, or set from an iterable with transformation and optional filtering.'],
      ],
      steps: [
        ['The interpreter loads a module', 'Top-level statements execute in order, so import is not textual inclusion and may have side effects.'],
        ['Indentation forms a block', 'A colon opens a suite after if, for, def, class, try, with, or match; equal indentation shows membership.'],
        ['Assignment binds a name', 'orders = [...] creates a list and binds orders to it. Another name may reference the same list.'],
        ['for requests items', 'for order in orders receives objects from the iterable. Use enumerate only when an index is genuinely needed.'],
        ['A comprehension builds a collection', 'The left expression transforms, for chooses the source, and a trailing if filters.'],
        ['def creates a function', 'The body does not run at definition time. Parameters bind to passed objects on a call.'],
        ['return ends the call', 'Without an explicit return a function returns None; several comma-separated values form a tuple.'],
      ],
      nuances: [
        ['and and or return an operand', 'The result need not be bool, so value or fallback incorrectly replaces valid zero, empty text, or an empty list.'],
        ['== and is ask different questions', '== checks value equality while is checks object identity. Use is for None and private sentinel objects.'],
        ['A slice is normally a shallow copy', 'items[:] creates a new list that still contains references to the same nested objects.'],
        ['dict is not a JavaScript object', 'Keys may have multiple hashable types, missing [] raises KeyError, and attribute access is a different protocol.'],
        ['Annotations do not validate runtime values', 'name: str helps an IDE and type checker, but ordinary CPython does not enforce the binding type.'],
        ['Loops may have else', 'The else branch runs when the loop finishes without break; it does not belong to the nearest if.'],
        ['Scope is not block-based', 'if and for do not create local scopes. Modules, functions, classes, and comprehensions normally do.'],
      ],
      pitfalls: [
        ['Indentation is only formatting style.', 'Indentation is part of the grammar and defines block boundaries.'],
        ['range(5) creates a list.', 'range creates a compact iterable; list(range(5)) materializes a list.'],
        ['dict.key is equivalent to object.key.', 'A normal dict uses data["key"] or data.get("key"); attributes follow another protocol.'],
        ['if value checks only true or false.', 'Truth testing also considers None, numeric zero, and empty collections false.'],
        ['A tuple is the Python replacement for const.', 'JS const blocks rebinding while tuple blocks mutation of its sequence; these are different guarantees.'],
        ['Type hints perform runtime validation.', 'Annotations are metadata unless a type checker or runtime library consumes them.'],
      ],
      codeIntro: 'Read the snippet in layers: identify collections and blocks, follow name bindings, then read the comprehension filter and formatting details.',
      codeNotes: [
        'A list of dictionaries is similar in shape to a JavaScript array of objects.',
        'The filtering if is written after for even though it controls which items enter the result.',
        'sum can consume a generator expression one value at a time.',
        '*middle gathers remaining unpacked values into a new list.',
        'The star before currency makes it keyword-only.',
      ],
      examples: [
        { title: 'Core collections', goal: 'Tell the built-in containers apart.', code: 'numbers = [1, 2, 3]                 # list\npoint = (10, 20)                    # tuple\nuser = {"id": 7, "name": "Ada"}  # dict\nroles = {"admin", "editor"}        # set', notes: ['Empty {} creates a dictionary; use set() for an empty set.', 'Nested mutable objects remain mutable inside a tuple.'] },
        { title: 'Safe dictionary access', goal: 'Distinguish a missing key from valid zero.', code: 'discount = payload.get("discount")\nif discount is None:\n    discount = 10\n\nquantity = payload["quantity"]', notes: ['get fits an optional key.', '[] fits a required contract that should fail when absent.'] },
        { title: 'Loop without a manual counter', goal: 'Read enumerate and pair unpacking.', code: 'for index, order in enumerate(orders, start=1):\n    print(index, order["id"])', notes: ['enumerate lazily yields (index, value) tuples.', 'The pair is unpacked on every iteration.'] },
        { title: 'Comprehension', goal: 'Recognize map and filter in Python form.', code: 'paid_ids = [\n    order["id"]\n    for order in orders\n    if order["status"] == "paid"\n]', notes: ['The result expression is written before for.', 'Prefer a normal loop when the logic becomes complex.'] },
        { title: 'Function parameters', goal: 'Understand positional, default, and keyword-only arguments.', code: 'def connect(host: str, port: int = 5432, *, timeout: float = 2.0):\n    return f"{host}:{port}; timeout={timeout}"\n\nconnect("db", timeout=1.5)', notes: ['Arguments after * must be named.', 'Annotations do not force CPython to check values.'] },
        { title: 'Module entry point', goal: 'Avoid starting the application on import.', code: 'def main() -> None:\n    print("start")\n\nif __name__ == "__main__":\n    main()', notes: ['Direct execution sets __name__ to __main__.', 'Import creates definitions without calling main.'] },
      ],
      questions: [
        'Why does orders_copy = orders not copy the list?',
        'Why is data.get("count") or 10 wrong for count=0?',
        'What does a list comprehension create?',
        'Why is is None preferable to == None?',
        'What runs when a module is imported for the first time?',
      ],
    },
  },

  'python-objects-functions': {
    title: 'Python objects, functions, and protocols',
    eyebrow: 'Identity · classes · generators · errors',
    summary: 'Read functions as values, classes, dataclasses, generators, decorators, exceptions, and context managers without importing JavaScript assumptions.',
    theory: 'Everything exposed to Python code—including functions, classes, and modules—is represented by objects. Compact syntax such as with, yield, property, and decorators delegates behavior to explicit object protocols.',
    watchFor: 'The CPython trace reveals shared mutable identity, the mutable-default trap, dataclass generation, lazy yield, structural matching, exception handling, and deterministic context cleanup.',
    expected: [
      'A class call creates an instance and methods receive self.',
      'Mutable default arguments persist between calls.',
      'Calling a generator function does not execute its body immediately.',
      'with invokes cleanup on normal and exceptional exits.',
      'A decorator is applied while a definition executes.',
    ],
    code: 'from dataclasses import dataclass\n\n@dataclass(slots=True)\nclass CartLine:\n    sku: str\n    price: int\n    quantity: int = 1\n\n    @property\n    def subtotal(self) -> int:\n        return self.price * self.quantity\n\ndef even_squares(limit):\n    for value in range(limit):\n        if value % 2 == 0:\n            yield value * value',
    learning: {
      plain: 'Much of Python meaning lives in object protocols: a function is a value, class creates a new type, a generator pauses at yield, with guarantees context exit, and a decorator replaces a name with the result of another call.',
      foundation: 'Functions, classes, and modules are objects. Attribute resolution follows the data model, bound methods receive the instance as self, exceptions unwind frames toward a matching handler, iter/next define iteration, and context managers implement enter/exit behavior.',
      why: 'This is where JS intuition creates hidden bugs: a mutable default survives calls, class attributes are shared, shallow copies retain nested references, and generator bodies do not execute until iteration.',
      codeLanguage: 'Python',
      snippetLabel: 'src/python-lab.py · educational snippet',
      runtimeCodeHint: 'The first file is the real CPython scenario; the second safely starts the child process and turns its JSON Lines into the live trace.',
      runtimeTraceConnection: 'Python calls emit(...) and prints JSON Lines to stdout. The Node bridge reads them without a shell, bounds runtime and output, and forwards events into the HTTP stream.',
      resources: [
        { label: 'Python Data Model', description: 'Objects, identity, types, attributes, special methods, and callables.', href: 'https://docs.python.org/3/reference/datamodel.html' },
        { label: 'Classes', description: 'Scopes, class and instance variables, inheritance, iterators, and generators.', href: 'https://docs.python.org/3/tutorial/classes.html' },
        { label: 'Errors and Exceptions', description: 'try, except, else, finally, raise, chaining, and cleanup.', href: 'https://docs.python.org/3/tutorial/errors.html' },
      ],
      runtimeLayers: [
        { title: 'NAMES', detail: 'bindings · scopes · closures', active: true },
        { title: 'OBJECTS', detail: 'identity · type · value' },
        { title: 'PROTOCOLS', detail: 'iteration · context · call' },
        { title: 'APPLICATION', detail: 'modules · classes · errors' },
      ],
      terms: [
        ['Identity', 'The identity of one concrete object. is asks whether two references point to that same object.'],
        ['Mutable', 'An object whose value can change without creating another object, such as list, dict, and set.'],
        ['Callable', 'An object accepted by call syntax (). Functions and classes are callable, and custom objects may implement __call__.'],
        ['Decorator', 'A callable that receives a function or class and binds the original name to its returned result.'],
        ['Generator', 'An iterator that preserves a frame and resumes execution between yield expressions.'],
        ['Context manager', 'An enter/exit protocol used by with for deterministic resource cleanup.'],
        ['Exception', 'An error object propagated up call frames until a compatible except catches it.'],
        ['dataclass', 'A standard-library decorator that generates common data-class methods such as __init__ and __repr__.'],
        ['Closure', 'A function plus references to free variables from an enclosing function scope.'],
        ['Module cache', 'sys.modules retains loaded modules, so repeated import normally returns the same module object.'],
      ],
      steps: [
        ['class executes its body', 'Python evaluates the class body in a namespace and then creates a class object.'],
        ['Calling the class creates an instance', '__new__ creates the object and __init__ initializes the existing instance.'],
        ['A method binds self', 'instance.method creates a bound method and passes the instance as the first argument.'],
        ['A decorator applies at definition time', '@decorator above def is equivalent to name = decorator(name).'],
        ['A generator starts on demand', 'Calling its function creates a generator; the body begins only under next or iteration.'],
        ['with guarantees exit', '__exit__ runs for normal flow and exceptions, making cleanup predictable.'],
        ['An exception searches for a handler', 'Frames unwind to a compatible except and finally runs on every exit path.'],
      ],
      nuances: [
        ['Defaults are evaluated once', 'Default objects are created when def executes, so a mutable default accumulates state.'],
        ['A class variable is shared', 'A mutable object in the class body is shared until an instance shadows that attribute.'],
        ['property can run expensive code', 'order.total may invoke arbitrary descriptor code and raise an exception.'],
        ['finally can replace a result', 'return inside finally suppresses an earlier result or exception and is usually a design bug.'],
        ['A generator is single-use', 'After StopIteration the same generator does not restart; call the generator function again.'],
        ['A closure retains objects', 'A captured object stays reachable while the inner function lives, just as in JavaScript.'],
        ['Private is mainly convention', '_name marks an internal API; __name uses name mangling but is not strict privacy.'],
      ],
      pitfalls: [
        ['items=[] creates a fresh list per call.', 'One default list is created when def executes and is reused.'],
        ['self is a special keyword.', 'It is the conventional name of the first instance-method parameter.'],
        ['yield permanently ends the function.', 'yield pauses its frame and the next next call resumes after it.'],
        ['except Exception catches absolutely everything.', 'System signals such as KeyboardInterrupt derive from BaseException instead.'],
        ['with only works with files.', 'The protocol also supports locks, transactions, tracing, and temporary state.'],
        ['Import merely declares a dependency.', 'The first import executes module top-level code and may perform I/O or mutate state.'],
      ],
      codeIntro: 'The runtime places several surprising protocols side by side: dataclass, shared list identity, a bad default, a generator, matching, an exception, and with cleanup.',
      codeNotes: [
        '@dataclass(slots=True) generates boilerplate and changes instance layout.',
        '@property exposes a descriptor with attribute syntax.',
        'append_bad returns a copy, but its hidden default list remains shared.',
        'yield preserves the frame and local bindings.',
        'match can destructure a mapping rather than merely switch on one scalar.',
        'StringIO is closed after with without a manual close call.',
      ],
      examples: [
        { title: 'Function as a value', goal: 'Recognize a callable without invoking it.', code: 'def normalize(value: str) -> str:\n    return value.strip().lower()\n\npipeline = [normalize, str.upper]\nfor transform in pipeline:\n    value = transform(value)', notes: ['A function name without () refers to the function object.', 'Each callable receives the previous result.'] },
        { title: 'Safe default', goal: 'Avoid sharing mutable state.', code: 'def add_tag(tag: str, tags: list[str] | None = None):\n    result = [] if tags is None else list(tags)\n    result.append(tag)\n    return result', notes: ['None is an immutable sentinel.', 'list(tags) avoids mutating the caller list.'] },
        { title: 'Data class', goal: 'Read dataclass and property syntax.', code: 'from dataclasses import dataclass\n\n@dataclass(frozen=True, slots=True)\nclass Money:\n    amount: int\n    currency: str = "USD"\n\n    @property\n    def label(self):\n        return f"{self.amount} {self.currency}"', notes: ['frozen is not deep immutability.', 'slots changes instance layout.'] },
        { title: 'Generator', goal: 'Process a stream lazily.', code: 'def read_valid(lines):\n    for line in lines:\n        text = line.strip()\n        if text:\n            yield text\n\nfor item in read_valid(file):\n    consume(item)', notes: ['The result is not stored in full.', 'The outer resource still needs cleanup.'] },
        { title: 'Exception chaining', goal: 'Add domain meaning without losing the cause.', code: 'try:\n    user = repository.get(user_id)\nexcept DatabaseError as error:\n    raise UserLoadError(user_id) from error\nelse:\n    return user\nfinally:\n    metrics.increment("load.attempt")', notes: ['raise ... from preserves the causal chain.', 'else runs only when try succeeds.'] },
        { title: 'Context manager', goal: 'Guarantee transaction cleanup.', code: 'with database.transaction() as transaction:\n    order = transaction.insert_order(payload)\n    transaction.insert_outbox(order)', notes: ['The concrete manager defines commit and rollback behavior.', 'An exception is passed into __exit__.'] },
      ],
      questions: [
        'When is a default argument evaluated?',
        'Why can instances share a class-level list?',
        'When does a generator body begin?',
        'Which methods does with invoke?',
        'Why is a property not necessarily a cheap field?',
      ],
    },
  },

  'cpython-runtime-asyncio': {
    title: 'CPython runtime, memory, GIL, and asyncio',
    eyebrow: 'Source → bytecode → frames → concurrency',
    summary: 'Trace how CPython compiles and executes code, owns objects, collects cycles, coordinates threads, and schedules asyncio tasks.',
    theory: 'Python is a language while CPython is one implementation. CPython compiles code blocks into code objects and bytecode executed in frames. Reference counting manages most lifetimes, cyclic GC supplements it, the usual build has a GIL, and asyncio is a separate cooperative scheduler library.',
    watchFor: 'A real CPython child process disassembles a function, inspects its frame, collects a reference cycle, reports its GIL configuration, schedules two tasks, and compares blocking time.sleep with asyncio.to_thread.',
    expected: [
      'Source is compiled into a code object before its bytecode executes.',
      'Every executing code block has a frame.',
      'Reference counting alone cannot reclaim an isolated reference cycle.',
      'Calling async def creates a coroutine; scheduling makes it run.',
      'Blocking the event-loop thread delays unrelated tasks.',
    ],
    code: 'async def fetch_pair():\n    first = asyncio.create_task(fetch("/first"))\n    second = asyncio.create_task(fetch("/second"))\n    return await asyncio.gather(first, second)\n\n# Blocking legacy I/O must leave the loop thread:\ndata = await asyncio.to_thread(legacy_read, path)',
    learning: {
      plain: 'Python is the language and CPython is its main implementation. CPython parses source, creates code objects with bytecode, and executes them in frames. The interpreter itself is not an event loop: an async scheduler exists only when a program runs asyncio.',
      foundation: 'Modules, function bodies, and class bodies are code blocks executed in frames. CPython compiles source to version-specific bytecode. Reference counting handles most object lifetime and cyclic GC handles cycles. In a regular GIL build, one thread at a time executes Python bytecode, while blocking I/O may release the GIL. asyncio adds an event loop, tasks, futures, and awaitables.',
      why: 'This model explains why async def starts nothing by itself, time.sleep freezes asyncio, threads help I/O but normally not pure-Python CPU, process pools serialize data, and RSS may not fall as soon as objects die.',
      codeLanguage: 'Python',
      snippetLabel: 'src/python-lab.py · educational snippet',
      runtimeCodeHint: 'The first file is the real CPython scenario; the second safely starts the child process and turns its JSON Lines into the live trace.',
      runtimeTraceConnection: 'Python calls emit(...) and prints JSON Lines to stdout. The Node bridge reads them without a shell, bounds runtime and output, and forwards events into the HTTP stream.',
      resources: [
        { label: 'Python Execution Model', description: 'Code blocks, frames, scopes, interpreters, and thread states.', href: 'https://docs.python.org/3/reference/executionmodel.html' },
        { label: 'dis — Python bytecode', description: 'Code-object disassembly and the version-specific nature of bytecode.', href: 'https://docs.python.org/3/library/dis.html' },
        { label: 'Garbage Collector', description: 'Cyclic GC generations and its relationship with CPython reference counting.', href: 'https://docs.python.org/3/library/gc.html' },
        { label: 'Thread states and GIL', description: 'GIL ownership, thread switching, and release around blocking I/O.', href: 'https://docs.python.org/3/c-api/threads.html' },
        { label: 'asyncio', description: 'Coroutines, tasks, event loops, queues, streams, and subprocess APIs.', href: 'https://docs.python.org/3/library/asyncio.html' },
        { label: 'Free-threaded Python', description: 'Optional GIL-disabled CPython builds supported from Python 3.13.', href: 'https://docs.python.org/3/howto/free-threading-python.html' },
      ],
      runtimeLayers: [
        { title: 'SOURCE', detail: 'tokens · AST · symbols', active: true },
        { title: 'CODE OBJECT', detail: 'constants · names · bytecode' },
        { title: 'CPYTHON VM', detail: 'frames · eval loop · objects' },
        { title: 'CONCURRENCY', detail: 'GIL · threads · asyncio · processes' },
      ],
      anchorModel: {
        label: 'CPython anchor model',
        title: 'The interpreter, GIL, and asyncio are different layers',
        intro: 'First ask whether bytecode is executing, threads are coordinating access to objects, or a coroutine has cooperatively yielded to an event loop.',
        checkpoints: [
          { badge: '01 · Compile', title: 'Source becomes a code object', description: 'The parser builds syntax structure and the compiler resolves scopes and emits bytecode.' },
          { badge: '02 · Execute', title: 'A frame executes bytecode', description: 'The frame holds code-block context and locals while the evaluation loop executes CPython instructions.' },
          { badge: '03 · Coordinate', title: 'A concurrency model is chosen', description: 'Threads share memory, processes isolate heaps, and asyncio switches tasks at suspension points.' },
        ],
        lanes: [
          { location: 'CPython memory', name: 'Reference count', rule: 'An object is often reclaimed immediately after its last strong reference disappears.' },
          { location: 'Cyclic collector', name: 'gc', rule: 'Supplements reference counting by finding isolated reference cycles.' },
          { location: 'Interpreter lock', name: 'GIL', rule: 'In a regular build it serializes Python bytecode across threads of one interpreter.' },
          { location: 'OS scheduling', name: 'thread / process', rule: 'A thread shares the heap; a process has separate memory and IPC.' },
          { location: 'Library scheduler', name: 'asyncio', rule: 'The loop resumes tasks after await; blocking code does not yield control.' },
        ],
        callouts: [
          { title: 'Python is not CPython', text: 'The language defines semantics while CPython is an implementation. PyPy and other runtimes may use different VM, JIT, memory, and cleanup behavior.' },
          { title: 'The GIL is not a thread-safety guarantee', text: 'Compound operations and shared mutable state still need synchronization; C extensions and free-threaded builds change assumptions further.' },
        ],
        exampleLabel: 'Cooperative asyncio scheduling',
        example: 'create_task(A, B) → main reaches await → A/B start → await suspends them → ready B resumes → A',
        footnote: 'If a coroutine calls time.sleep or computes for a long time without await, the loop cannot run the other tasks.',
      },
      terms: [
        ['CPython', 'The reference and most widely used Python implementation, written primarily in C.'],
        ['Code object', 'A compiled code block containing bytecode, constants, names, and metadata.'],
        ['Bytecode', 'Instructions for the CPython VM; not a stable machine-code contract and different across versions.'],
        ['Frame', 'A code-block execution context with code, locals, globals, instruction state, and call relationships.'],
        ['Reference counting', 'The primary CPython lifetime mechanism: an object may be reclaimed once strong references are gone.'],
        ['Cyclic GC', 'A collector that finds unreachable object groups that reference each other.'],
        ['GIL', 'The Global Interpreter Lock required by a thread executing Python objects and bytecode in a regular CPython build.'],
        ['Coroutine', 'A suspendable computation object returned by calling async def; it is not scheduled by itself.'],
        ['Task', 'An asyncio wrapper that schedules a coroutine and stores its result or exception.'],
        ['Awaitable', 'An object accepted by await: coroutine, Task, Future, or a compatible protocol implementation.'],
        ['Future', 'A low-level future-result holder connecting callback APIs to an awaiting task.'],
        ['Free-threaded build', 'An optional CPython build without the GIL that requires compatible libraries and extensions.'],
      ],
      steps: [
        ['Source is parsed', 'The parser checks grammar and builds an AST; SyntaxError happens before that code block executes.'],
        ['The compiler creates a code object', 'Names and scopes are classified, literals become constants, and operations become bytecode.'],
        ['def creates a function object', 'The function links a code object with globals, defaults, and closure cells.'],
        ['A call creates a frame', 'Arguments bind to parameters and the evaluation loop begins executing bytecode.'],
        ['Bindings retain objects', 'Removing a binding reduces reachability while cycles require supplemental collection.'],
        ['A thread enters the interpreter', 'Regular CPython requires the GIL and commonly releases it around blocking I/O.'],
        ['asyncio resumes a task', 'await yields control when needed and later readiness makes the task runnable.'],
        ['CPU work chooses another path', 'Long pure-Python CPU usually moves to processes, native code, or a validated free-threaded architecture.'],
      ],
      nuances: [
        ['async def does not run its body', 'Calling it creates a coroutine object; await, create_task, or another scheduler is needed.'],
        ['await does not always switch tasks', 'An already-ready awaitable may return without an actual suspension.'],
        ['The GIL belongs to a CPython configuration', 'Free-threaded builds arrived in 3.13 and other implementations have their own models.'],
        ['Threads remain useful for I/O', 'Blocking I/O and many native extensions release the GIL and overlap waiting.'],
        ['Processes do not share a normal heap', 'Startup, IPC, and serialization can cost more than a small CPU task.'],
        ['del does not directly delete an object', 'It removes a binding; other references retain the object and allocators may retain arenas.'],
        ['Bytecode is a diagnostic, not an API', 'dis is useful, but opcodes are version-specific and profiling comes first.'],
        ['One asyncio loop normally belongs to one thread', 'Most asyncio objects are not thread-safe; cross-thread calls need dedicated APIs.'],
      ],
      pitfalls: [
        ['Python executes source line by line without compilation.', 'CPython compiles code blocks into code objects and bytecode first.'],
        ['The GIL prevents race conditions.', 'Shared state and compound operations still require locks or queues.'],
        ['asyncio makes a blocking library non-blocking.', 'A synchronous call blocks the loop unless replaced or explicitly offloaded.'],
        ['await starts another thread.', 'Normally the same task and thread yield control to the event loop until readiness.'],
        ['Threads speed up pure-Python CPU.', 'Regular CPython does not run that bytecode in parallel; use processes, native code, or a free-threaded build.'],
        ['gc.collect guarantees a lower RSS.', 'Objects become available to the allocator, but the allocator and OS may retain arenas.'],
      ],
      codeIntro: 'The scenario starts a real CPython child process and inspects disassembly, a frame, a reference cycle, GIL configuration, asyncio scheduling, and blocking versus to_thread.',
      codeNotes: [
        'dis.get_instructions reads current-version bytecode without hard-coded opcode names.',
        'sys._getframe reveals the execution frame and is a CPython-oriented API.',
        'weakref observes lifetime without retaining the target strongly.',
        'gc.collect is forced only for a controlled experiment.',
        'create_task schedules a coroutine; its body runs after control returns to the loop.',
        'time.sleep blocks the thread while asyncio.to_thread moves that call away from the loop thread.',
      ],
      examples: [
        { title: 'Coroutine and task', goal: 'Separate a created computation from scheduled work.', code: 'async def load_user(user_id: int):\n    return await repository.get(user_id)\n\ncoroutine = load_user(7)\ntask = asyncio.create_task(coroutine)\nuser = await task', notes: ['A lost coroutine performs no useful work.', 'A Task stores a result or exception.'] },
        { title: 'Concurrent I/O waiting', goal: 'Avoid sequentially waiting for independent operations.', code: 'user, orders = await asyncio.gather(\n    load_user(user_id),\n    load_orders(user_id),\n)', notes: ['Concurrency does not imply threads.', 'Errors and cancellation are part of the contract.'] },
        { title: 'Offload blocking I/O', goal: 'Keep the event-loop thread responsive.', code: 'def read_legacy_file(path: str) -> bytes:\n    return legacy_client.read(path)\n\ndata = await asyncio.to_thread(read_legacy_file, path)', notes: ['to_thread does not make the library intrinsically async.', 'Bound the amount of offloaded work.'] },
        { title: 'CPU in a process pool', goal: 'Use multiple cores for pure-Python work.', code: 'pool = ProcessPoolExecutor()\nresult = await asyncio.get_running_loop().run_in_executor(\n    pool, calculate_report, payload\n)', notes: ['The function and payload must be serializable.', 'Keep the pool long-lived and bounded.'] },
        { title: 'Bytecode diagnostics', goal: 'Inspect VM instructions.', code: 'import dis\n\ndef total(values):\n    return sum(value * 2 for value in values)\n\ndis.dis(total)', notes: ['Opcode names vary by version.', 'Profile before inspecting bytecode.'] },
        { title: 'GC observation', goal: 'Measure collection instead of guessing from RSS.', code: 'import gc\n\nbefore = gc.get_stats()\ncollected = gc.collect()\nafter = gc.get_stats()', notes: ['Collecting in a request path does not fix a leak.', 'Find retaining references instead.'] },
      ],
      questions: [
        'How does Python differ from CPython?',
        'When does an async def body begin?',
        'Why does time.sleep delay other tasks?',
        'Why does reference counting need cyclic GC?',
        'Why does the GIL not remove the need for locks?',
        'When is a process pool slower than sequential code?',
      ],
    },
  },
};
