global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: node-loop-lab
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - node-loop-lab:3000
