export const pythonLearningRu = {
  'python-syntax-for-js': {
    plain:
      'Python читается не как JavaScript без фигурных скобок. Отступы задают блоки, имена ссылаются на объекты, коллекции имеют разные свойства, а многие привычные циклы заменяются прямым обходом iterable. Цель главы — научиться видеть структуру чужого файла, даже если вы ещё не готовы писать библиотеку самостоятельно.',
    foundation:
      'Файл .py состоит из statements и expressions. Присваивание связывает имя с объектом; оно не объявляет ячейку фиксированного типа. Блок начинается после двоеточия и определяется одинаковым отступом. def создаёт функцию-объект, import выполняет и кэширует модуль, for запрашивает элементы у iterable, а with и try описывают управление ресурсами и ошибками.',
    why:
      'JS-разработчику опаснее всего ложные аналогии: dict похож на object, но является mapping; list похож на Array, но slicing и comprehension меняют способ чтения; None не равен undefined; is проверяет идентичность, а не значение.',
    codeLanguage: 'Python',
    snippetLabel: 'src/python-lab.py · учебный фрагмент',
    runtimeCodeHint: 'Первый файл — настоящий CPython-сценарий; второй безопасно запускает child process и переводит его JSON Lines в live trace.',
    runtimeTraceConnection: 'Python вызывает emit(...) и печатает JSON Lines в stdout. Node bridge читает строки без shell, ограничивает время и объём вывода и передаёт события HTTP stream.',
    resources: [
      { label: 'The Python Tutorial', description: 'Официальный путь по синтаксису, коллекциям, модулям, ошибкам и классам.', href: 'https://docs.python.org/3/tutorial/' },
      { label: 'Built-in Types', description: 'Точное поведение list, tuple, dict, set, str, truth testing и операций.', href: 'https://docs.python.org/3/library/stdtypes.html' },
      { label: 'Control Flow', description: 'if, for, range, match, def, параметры и распаковка аргументов.', href: 'https://docs.python.org/3/tutorial/controlflow.html' },
    ],
    runtimeLayers: [
      { title: 'PYTHON SOURCE', detail: '.py · statements · expressions', active: true },
      { title: 'PARSER', detail: 'tokens · AST · scopes' },
      { title: 'CPYTHON', detail: 'code objects · bytecode · frames' },
      { title: 'OBJECTS', detail: 'types · collections · stdlib' },
    ],
    terms: [
      { name: 'Имя', description: 'Идентификатор, связанный с объектом. Присваивание другого объекта меняет binding имени, а не тип отдельной переменной-ячейки.' },
      { name: 'Statement', description: 'Инструкция вроде if, for, import, return или assignment. Она управляет выполнением и не всегда производит значение.' },
      { name: 'Expression', description: 'Фрагмент, который вычисляется в объект-значение: вызов функции, арифметика, comprehension или доступ по индексу.' },
      { name: 'Iterable', description: 'Объект, элементы которого можно получать по одному в for, comprehension, sum, list и других потребителях.' },
      { name: 'list', description: 'Изменяемая упорядоченная последовательность. Ближайшая аналогия — JS Array, но методы и модель копирования отличаются.' },
      { name: 'tuple', description: 'Неизменяемая последовательность. Часто используется для фиксированной группы значений и распаковки.' },
      { name: 'dict', description: 'Mapping ключ → значение. Ключ должен быть hashable; доступ через [] выбрасывает KeyError, а get возвращает fallback.' },
      { name: 'set', description: 'Коллекция уникальных hashable-элементов с быстрыми membership-проверками и операциями множеств.' },
      { name: 'None', description: 'Единственный объект отсутствующего значения. Обычно сравнивается через is None, а не через ==.' },
      { name: 'Comprehension', description: 'Выражение, которое строит list, dict или set из iterable с преобразованием и необязательным фильтром.' },
    ],
    steps: [
      { title: 'Интерпретатор загружает модуль', description: 'Top-level statements файла выполняются по порядку. Поэтому import — не текстовая вставка и может иметь side effects.' },
      { title: 'Отступ формирует блок', description: 'После if, for, def, class, try, with или match двоеточие открывает suite; одинаковый indentation показывает принадлежность строк.' },
      { title: 'Assignment связывает имя', description: 'orders = [...] создаёт list и привязывает к нему имя orders. Другое имя может ссылаться на тот же list.' },
      { title: 'for запрашивает элементы', description: 'for order in orders получает объекты iterable. Индекс нужен только когда вы явно вызываете enumerate.' },
      { title: 'Comprehension строит коллекцию', description: 'Выражение слева преобразует элемент, for задаёт источник, if справа фильтрует.' },
      { title: 'def создаёт функцию', description: 'Тело не выполняется при объявлении. Параметры связываются с переданными объектами во время вызова.' },
      { title: 'return завершает вызов', description: 'Без явного return функция возвращает None. Несколько значений фактически упаковываются в tuple.' },
    ],
    nuances: [
      { title: 'and и or возвращают operand', description: 'Результатом может быть не bool. Поэтому value or fallback ошибочно заменит допустимые 0, пустую строку или пустой list.' },
      { title: '== и is отвечают на разные вопросы', description: '== проверяет равенство значений, is сравнивает идентичность объектов. is нужен для None и специальных sentinel-объектов.' },
      { title: 'Срез обычно создаёт shallow copy', description: 'items[:] возвращает новый list с теми же ссылками на вложенные элементы, а не глубокий клон.' },
      { title: 'dict — не JavaScript object', description: 'Ключами могут быть разные hashable-типы; отсутствующий [] даёт KeyError; attribute access и mapping access не одно и то же.' },
      { title: 'Аннотации не валидируют runtime', description: 'name: str помогает IDE и type checker, но обычный CPython не запрещает позднее связать name с объектом другого типа.' },
      { title: 'У for и while бывает else', description: 'else выполняется, если цикл завершился без break. Это не аналог else у ближайшего if.' },
      { title: 'Scope не блочный', description: 'if и for не создают отдельный local scope. Новый scope обычно дают module, function, class и comprehension.' },
    ],
    pitfalls: [
      { myth: 'Отступы — только стиль форматирования.', fact: 'Отступы являются частью грамматики и определяют границы блока.' },
      { myth: 'range(5) создаёт list [0, 1, 2, 3, 4].', fact: 'range создаёт компактный iterable; list появится после явного list(range(5)).' },
      { myth: 'dict.key — аналог object.key.', fact: 'Обычный dict читается через data["key"] или data.get("key"). Атрибуты — другой протокол.' },
      { myth: 'if value проверяет только true/false.', fact: 'Python вызывает truth testing: ложными также считаются None, ноль и пустые коллекции.' },
      { myth: 'const из JavaScript заменяется tuple.', fact: 'const запрещает перепривязку binding, tuple запрещает изменение своей последовательности. Это разные гарантии.' },
      { myth: 'Type hints выполняют runtime-валидацию.', fact: 'Аннотации — metadata. Для проверки нужны type checker или отдельная runtime-библиотека.' },
    ],
    codeIntro:
      'Читайте фрагмент слоями: найдите созданные коллекции и блоки, затем проследите имена, фильтр comprehension и только после этого детали форматирования строки.',
    codeNotes: [
      'list из dict — форма данных, похожая на массив объектов JavaScript.',
      'Условие if находится после for внутри comprehension, хотя фильтрация происходит до попадания элемента в результат.',
      'sum получает generator expression и потребляет значения по одному.',
      '*middle при распаковке собирает оставшиеся элементы в новый list.',
      'Звёздочка перед currency делает параметр keyword-only.',
    ],
    examples: [
      { title: 'Основные коллекции', goal: 'Различать встроенные контейнеры.', code: 'numbers = [1, 2, 3]                 # list\npoint = (10, 20)                    # tuple\nuser = {"id": 7, "name": "Ada"}  # dict\nroles = {"admin", "editor"}        # set', notes: ['{} без элементов создаёт dict; пустой set записывается set().', 'Вложенные mutable-объекты остаются изменяемыми даже внутри tuple.'] },
      { title: 'Безопасное чтение dict', goal: 'Отличать отсутствие ключа от допустимого нуля.', code: 'discount = payload.get("discount")\nif discount is None:\n    discount = 10\n\nquantity = payload["quantity"]', notes: ['get удобен для необязательного ключа.', '[] полезен, когда отсутствие ключа должно считаться ошибкой контракта.'] },
      { title: 'Цикл без ручного индекса', goal: 'Читать enumerate и распаковку пары.', code: 'for index, order in enumerate(orders, start=1):\n    print(index, order["id"])', notes: ['enumerate лениво выдаёт tuples (index, value).', 'index и order связываются распаковкой на каждой итерации.'] },
      { title: 'Comprehension', goal: 'Увидеть map и filter в Python-форме.', code: 'paid_ids = [\n    order["id"]\n    for order in orders\n    if order["status"] == "paid"\n]', notes: ['Выражение результата записано перед for.', 'Для сложной логики обычный for часто читается лучше.'] },
      { title: 'Функция и параметры', goal: 'Понять positional, default и keyword-only arguments.', code: 'def connect(host: str, port: int = 5432, *, timeout: float = 2.0):\n    return f"{host}:{port}; timeout={timeout}"\n\nconnect("db", timeout=1.5)', notes: ['После * параметры передаются только по имени.', 'Аннотации не заставляют CPython проверять типы.'] },
      { title: 'Entry point модуля', goal: 'Не запускать приложение при import.', code: 'def main() -> None:\n    print("start")\n\nif __name__ == "__main__":\n    main()', notes: ['При прямом запуске __name__ равен __main__.', 'При import функции создаются, но main автоматически не вызывается.'] },
    ],
    questions: [
      'Почему orders_copy = orders не создаёт копию list?',
      'Чем data.get("count") or 10 опасен при count=0?',
      'Что создаёт [x * 2 for x in values if x > 0]?',
      'Почему is None корректнее == None?',
      'Что выполнится при import модуля впервые?',
    ],
  },

  'python-objects-functions': {
    plain:
      'Большая часть смысла Python спрятана в протоколах объектов: функция может быть значением, class создаёт новый тип, generator приостанавливается на yield, with гарантирует выход из контекста, а decorator заменяет объект результатом другого вызова.',
    foundation:
      'В Python всё, включая функции, классы и модули, представлено объектами. Атрибуты разрешаются через data model, методы получают instance как первый параметр self, исключения раскручивают стек до подходящего except, iter/next образуют протокол итерации, а context manager реализует __enter__/__exit__.',
    why:
      'Здесь JS-интуиция чаще всего даёт скрытые баги: mutable default живёт между вызовами, class attribute разделяется instances, shallow copy сохраняет вложенные ссылки, а generator не выполняет тело до начала итерации.',
    codeLanguage: 'Python',
    snippetLabel: 'src/python-lab.py · учебный фрагмент',
    runtimeCodeHint: 'Первый файл — настоящий CPython-сценарий; второй безопасно запускает child process и переводит его JSON Lines в live trace.',
    runtimeTraceConnection: 'Python вызывает emit(...) и печатает JSON Lines в stdout. Node bridge читает строки без shell, ограничивает время и объём вывода и передаёт события HTTP stream.',
    resources: [
      { label: 'Python Data Model', description: 'Объекты, identity, types, attributes, special methods и callables.', href: 'https://docs.python.org/3/reference/datamodel.html' },
      { label: 'Classes', description: 'Scopes, class/instance variables, inheritance, iterators и generators.', href: 'https://docs.python.org/3/tutorial/classes.html' },
      { label: 'Errors and Exceptions', description: 'try/except/else/finally, raise, chaining и cleanup.', href: 'https://docs.python.org/3/tutorial/errors.html' },
    ],
    runtimeLayers: [
      { title: 'NAMES', detail: 'bindings · scopes · closures', active: true },
      { title: 'OBJECTS', detail: 'identity · type · value' },
      { title: 'PROTOCOLS', detail: 'iteration · context · call' },
      { title: 'APPLICATION', detail: 'modules · classes · errors' },
    ],
    terms: [
      { name: 'Identity', description: 'Идентичность конкретного объекта. Оператор is отвечает, являются ли две ссылки одним объектом.' },
      { name: 'Mutable', description: 'Объект, значение которого можно изменить без создания нового объекта: например list, dict и set.' },
      { name: 'Callable', description: 'Объект, который можно вызвать через (). Функции и классы callable; объект может реализовать __call__.' },
      { name: 'Decorator', description: 'Callable, получающий функцию или class и связывающий исходное имя с возвращённым результатом.' },
      { name: 'Generator', description: 'Iterator, который сохраняет frame и продолжает выполнение между yield.' },
      { name: 'Context manager', description: 'Объект протокола входа/выхода, который with использует для детерминированного cleanup.' },
      { name: 'Exception', description: 'Объект ошибки, передаваемый вверх по call stack, пока подходящий except не перехватит его.' },
      { name: 'dataclass', description: 'Decorator стандартной библиотеки, генерирующий __init__, __repr__ и другие типичные методы класса данных.' },
      { name: 'Closure', description: 'Функция вместе со ссылками на free variables из enclosing function scope.' },
      { name: 'Module cache', description: 'sys.modules хранит загруженные модули; повторный import обычно возвращает тот же object.' },
    ],
    steps: [
      { title: 'class выполняет body', description: 'Python выполняет class body в namespace и затем создаёт class object. Это executable statement.' },
      { title: 'Вызов class создаёт instance', description: '__new__ создаёт объект, __init__ инициализирует уже созданный instance.' },
      { title: 'Метод связывается с self', description: 'При instance.method(...) Python создаёт bound method и передаёт instance первым аргументом.' },
      { title: 'Decorator применяется при определении', description: '@decorator над def эквивалентен name = decorator(name).' },
      { title: 'Generator стартует по требованию', description: 'Вызов generator function создаёт object. Тело начинает выполняться только при next или обходе.' },
      { title: 'with гарантирует выход', description: '__exit__ вызывается и при normal flow, и при exception, что делает cleanup предсказуемым.' },
      { title: 'Exception ищет handler', description: 'Стек раскручивается до совместимого except; finally выполняется при любом способе выхода.' },
    ],
    nuances: [
      { title: 'Defaults вычисляются один раз', description: 'Значения defaults создаются во время выполнения def. Mutable default поэтому накапливает состояние.' },
      { title: 'Class variable разделяется', description: 'Mutable-объект из class body общий для instances, пока attribute не переопределён на instance.' },
      { title: 'property может выполнять дорогой код', description: 'Доступ order.total вызывает descriptor/property и может даже выбросить exception.' },
      { title: 'finally может подменить результат', description: 'return внутри finally подавляет ранее возвращаемое значение или exception. Обычно это ошибка.' },
      { title: 'Generator одноразовый', description: 'После StopIteration тот же generator не начнётся заново; нужно снова вызвать generator function.' },
      { title: 'Closure удерживает объект', description: 'Пока живёт внутренняя функция, captured object остаётся достижимым — как замыкание в JavaScript.' },
      { title: 'Private — в основном соглашение', description: '_name обозначает internal API; __name применяет name mangling, но не строгую приватность.' },
    ],
    pitfalls: [
      { myth: 'items=[] создаёт новый list на каждый вызов.', fact: 'Один default list создаётся при выполнении def и переиспользуется.' },
      { myth: 'self — специальное ключевое слово.', fact: 'Это обычное имя первого параметра instance method и важное соглашение.' },
      { myth: 'yield навсегда завершает функцию.', fact: 'yield приостанавливает frame; следующий next продолжает код после остановки.' },
      { myth: 'except Exception ловит вообще всё.', fact: 'Системные сигналы вроде KeyboardInterrupt наследуются от BaseException.' },
      { myth: 'with работает только с файлами.', fact: 'Протокол подходит для locks, transactions, tracing и временного состояния.' },
      { myth: 'Import только объявляет зависимость.', fact: 'Первый import выполняет top-level code и может совершить I/O или изменить state.' },
    ],
    codeIntro:
      'Runtime показывает dataclass, общую identity mutable list, ошибочный default, generator, pattern matching, exception и cleanup через with.',
    codeNotes: [
      '@dataclass(slots=True) генерирует boilerplate и ограничивает обычный instance dictionary.',
      '@property превращает method в descriptor, читаемый как attribute.',
      'append_bad возвращает копию, но его скрытый default list остаётся общим.',
      'yield сохраняет frame и locals между итерациями.',
      'match сопоставляет структуру mapping, а не делает простой scalar switch.',
      'StringIO после with закрыт без ручного close.',
    ],
    examples: [
      { title: 'Функция как значение', goal: 'Увидеть callable без вызова.', code: 'def normalize(value: str) -> str:\n    return value.strip().lower()\n\npipeline = [normalize, str.upper]\nresult = "  Ada  "\nfor transform in pipeline:\n    result = transform(result)', notes: ['Имя функции без () ссылается на function object.', 'Каждый callable получает результат предыдущего.'] },
      { title: 'Безопасный default', goal: 'Не делить mutable state.', code: 'def add_tag(tag: str, tags: list[str] | None = None):\n    result = [] if tags is None else list(tags)\n    result.append(tag)\n    return result', notes: ['None — immutable sentinel.', 'list(tags) не изменяет list вызывающей стороны.'] },
      { title: 'Класс данных', goal: 'Читать dataclass и property.', code: 'from dataclasses import dataclass\n\n@dataclass(frozen=True, slots=True)\nclass Money:\n    amount: int\n    currency: str = "RUB"\n\n    @property\n    def label(self):\n        return f"{self.amount} {self.currency}"', notes: ['frozen не даёт глубокой immutable-гарантии.', 'slots меняет layout instance.'] },
      { title: 'Generator', goal: 'Обрабатывать поток лениво.', code: 'def read_valid(lines):\n    for line in lines:\n        text = line.strip()\n        if text:\n            yield text\n\nfor item in read_valid(file):\n    consume(item)', notes: ['Результат не хранится целиком.', 'Внешний ресурс всё равно нужно закрыть.'] },
      { title: 'Exception chaining', goal: 'Добавить domain-смысл без потери причины.', code: 'try:\n    user = repository.get(user_id)\nexcept DatabaseError as error:\n    raise UserLoadError(user_id) from error\nelse:\n    return user\nfinally:\n    metrics.increment("load.attempt")', notes: ['raise ... from сохраняет causal chain.', 'else выполняется только без exception в try.'] },
      { title: 'Context manager', goal: 'Гарантировать transaction cleanup.', code: 'with database.transaction() as transaction:\n    order = transaction.insert_order(payload)\n    transaction.insert_outbox(order)', notes: ['Commit/rollback определяет конкретный manager.', 'Exception передаётся в __exit__.'] },
    ],
    questions: [
      'Когда вычисляется default argument?',
      'Почему instances могут разделить class-level list?',
      'Когда generator body начинает выполняться?',
      'Какие методы вызывает with?',
      'Почему property нельзя автоматически считать дешёвым полем?',
    ],
  },

  'cpython-runtime-asyncio': {
    plain:
      'Python — язык, а CPython — его основная реализация. CPython разбирает source, создаёт code objects с bytecode и выполняет их во frames. Сам интерпретатор не является Event Loop: асинхронный планировщик появляется только когда программа запускает asyncio.',
    foundation:
      'Модуль, function body и class body являются code blocks и исполняются во frames. В CPython source компилируется в bytecode для evaluation loop; opcodes меняются между версиями. Объекты прежде всего освобождаются reference counting, а cyclic GC дополняет его для циклов. В обычной GIL-сборке один thread одновременно выполняет Python bytecode, хотя blocking I/O освобождает GIL. asyncio поверх этого предоставляет event loop, Tasks, Futures и awaitables.',
    why:
      'Модель объясняет, почему async def сам ничего не запускает, time.sleep замораживает asyncio, threads помогают I/O, но обычно не ускоряют pure-Python CPU, ProcessPool требует сериализации, а RSS может не упасть сразу после удаления объектов.',
    codeLanguage: 'Python',
    snippetLabel: 'src/python-lab.py · учебный фрагмент',
    runtimeCodeHint: 'Первый файл — настоящий CPython-сценарий; второй безопасно запускает child process и переводит его JSON Lines в live trace.',
    runtimeTraceConnection: 'Python вызывает emit(...) и печатает JSON Lines в stdout. Node bridge читает строки без shell, ограничивает время и объём вывода и передаёт события HTTP stream.',
    resources: [
      { label: 'Python Execution Model', description: 'Code blocks, frames, scopes, interpreters и thread states.', href: 'https://docs.python.org/3/reference/executionmodel.html' },
      { label: 'dis — Python bytecode', description: 'Дизассемблер code objects и изменяемость bytecode между версиями.', href: 'https://docs.python.org/3/library/dis.html' },
      { label: 'Garbage Collector', description: 'Cyclic GC, поколения и связь с reference counting CPython.', href: 'https://docs.python.org/3/library/gc.html' },
      { label: 'Thread states and GIL', description: 'GIL, переключение threads и освобождение lock на blocking I/O.', href: 'https://docs.python.org/3/c-api/threads.html' },
      { label: 'asyncio', description: 'Coroutines, Tasks, event loop, queues, streams и subprocess APIs.', href: 'https://docs.python.org/3/library/asyncio.html' },
      { label: 'Free-threaded Python', description: 'Опциональные CPython-сборки без GIL начиная с Python 3.13.', href: 'https://docs.python.org/3/howto/free-threading-python.html' },
    ],
    runtimeLayers: [
      { title: 'SOURCE', detail: 'tokens · AST · symbols', active: true },
      { title: 'CODE OBJECT', detail: 'constants · names · bytecode' },
      { title: 'CPYTHON VM', detail: 'frames · eval loop · objects' },
      { title: 'CONCURRENCY', detail: 'GIL · threads · asyncio · processes' },
    ],
    anchorModel: {
      label: 'Опорная модель CPython',
      title: 'Интерпретатор, GIL и asyncio — три разных слоя',
      intro: 'Сначала определите: выполняется ли bytecode, управляется ли доступ threads к objects или coroutine добровольно отдала управление event loop.',
      checkpoints: [
        { badge: '01 · Compile', title: 'Source становится code object', description: 'Parser строит синтаксическую структуру, compiler определяет scopes и выпускает bytecode.' },
        { badge: '02 · Execute', title: 'Frame выполняет bytecode', description: 'Frame хранит context code block и locals. Evaluation loop исполняет инструкции CPython.' },
        { badge: '03 · Coordinate', title: 'Выбирается concurrency model', description: 'Threads делят память, processes изолируют heaps, asyncio переключает Tasks в точках suspension.' },
      ],
      lanes: [
        { location: 'CPython memory', name: 'Reference count', rule: 'Объект часто освобождается сразу после исчезновения последней сильной ссылки.' },
        { location: 'Cyclic collector', name: 'gc', rule: 'Дополняет refcount и обнаруживает изолированные циклы ссылок.' },
        { location: 'Interpreter lock', name: 'GIL', rule: 'В обычной сборке сериализует Python bytecode threads одного interpreter.' },
        { location: 'OS scheduling', name: 'thread / process', rule: 'Thread делит heap; process имеет отдельную память и IPC.' },
        { location: 'Library scheduler', name: 'asyncio', rule: 'Loop возобновляет Tasks после await; blocking-код управление не отдаёт.' },
      ],
      callouts: [
        { title: 'Python не равен CPython', text: 'Язык задаёт semantics, CPython — implementation. PyPy и другие runtimes могут иначе устроить VM, JIT, память и timing cleanup.' },
        { title: 'GIL не делает код thread-safe', text: 'Составные операции и shared mutable state требуют синхронизации; C-extensions и free-threaded builds дополнительно меняют предпосылки.' },
      ],
      exampleLabel: 'Cooperative asyncio scheduling',
      example: 'create_task(A, B) → main достигает await → A/B стартуют → await приостанавливает их → готовый B возобновляется → A',
      footnote: 'Если coroutine вызывает time.sleep или долго считает без await, loop не получает управление и остальные Tasks ждут.',
    },
    terms: [
      { name: 'CPython', description: 'Эталонная и наиболее распространённая реализация Python, написанная преимущественно на C.' },
      { name: 'Code object', description: 'Скомпилированное представление code block: bytecode, constants, names и metadata.' },
      { name: 'Bytecode', description: 'Инструкции VM CPython. Это не стабильный machine-code контракт и они меняются между версиями.' },
      { name: 'Frame', description: 'Контекст code block: code object, locals, globals, instruction state и связь с вызовами.' },
      { name: 'Reference counting', description: 'Основной механизм lifetime объектов CPython: объект можно освободить, когда сильных ссылок нет.' },
      { name: 'Cyclic GC', description: 'Collector, находящий недостижимые группы objects, которые ссылаются друг на друга.' },
      { name: 'GIL', description: 'Global Interpreter Lock обычной CPython-сборки, требуемый thread для Python objects и bytecode.' },
      { name: 'Coroutine', description: 'Объект приостанавливаемого вычисления, полученный вызовом async def. Сам ещё не запланирован.' },
      { name: 'Task', description: 'Обёртка asyncio, которая планирует coroutine на event loop и хранит result или exception.' },
      { name: 'Awaitable', description: 'Объект для await: coroutine, Task, Future или реализация соответствующего протокола.' },
      { name: 'Future', description: 'Контейнер будущего результата, связывающий callback/API с ожидающей Task.' },
      { name: 'Free-threaded build', description: 'Опциональная сборка CPython без GIL, требующая готовности libraries и extensions.' },
    ],
    steps: [
      { title: 'Source разбирается', description: 'Parser проверяет grammar и строит AST; SyntaxError возникает до выполнения code block.' },
      { title: 'Compiler создаёт code object', description: 'Имена/scopes классифицируются, literals становятся constants, операции — bytecode.' },
      { title: 'def создаёт function object', description: 'Function связывает code object с globals, defaults и closure.' },
      { title: 'Вызов создаёт frame', description: 'Arguments связываются с parameters, evaluation loop начинает bytecode.' },
      { title: 'Bindings удерживают objects', description: 'Удаление binding снижает reachability; cycles требует дополнительного GC.' },
      { title: 'Thread получает interpreter', description: 'В обычном CPython нужен GIL; на blocking I/O он обычно освобождается.' },
      { title: 'asyncio возобновляет Task', description: 'await возвращает управление loop, а готовность позже делает Task runnable.' },
      { title: 'CPU выбирает другой путь', description: 'Долгий pure-Python CPU обычно выносят в process pool, native code или проверенную free-threaded архитектуру.' },
    ],
    nuances: [
      { title: 'async def не запускает body', description: 'Вызов создаёт coroutine object. Нужны await, create_task или scheduler.' },
      { title: 'await не всегда переключает Task', description: 'Если awaitable уже готов, реальной suspension может не произойти.' },
      { title: 'GIL — свойство configuration CPython', description: 'Free-threaded builds появились в 3.13, другие implementations имеют свои модели.' },
      { title: 'Threads полезны для I/O', description: 'Blocking I/O и многие native extensions освобождают GIL и перекрывают ожидание.' },
      { title: 'Processes не делят обычный heap', description: 'Startup, IPC и serialization могут стоить дороже короткой CPU-задачи.' },
      { title: 'del не удаляет object напрямую', description: 'Он убирает binding; object живёт при оставшихся ссылках, allocator может сохранить arena.' },
      { title: 'Bytecode — диагностика, не API', description: 'dis полезен, но opcodes зависят от версии. Сначала нужен profiler.' },
      { title: 'Один asyncio loop обычно в одном thread', description: 'Большинство asyncio objects не thread-safe; из другого thread нужны специальные APIs.' },
    ],
    pitfalls: [
      { myth: 'Python построчно выполняет source без компиляции.', fact: 'CPython компилирует code blocks в code objects/bytecode и затем выполняет их.' },
      { myth: 'GIL исключает race conditions.', fact: 'Shared state и составные операции требуют locks/queues.' },
      { myth: 'asyncio делает blocking library неблокирующей.', fact: 'Sync-вызов блокирует loop; нужен async API или explicit offload.' },
      { myth: 'await запускает другой thread.', fact: 'Обычно та же Task и thread отдают управление loop до готовности awaitable.' },
      { myth: 'Threads ускоряют pure-Python CPU.', fact: 'В обычном CPython bytecode не идёт параллельно; используют processes/native/free-threaded build.' },
      { myth: 'gc.collect гарантированно уменьшает RSS.', fact: 'Objects становятся доступны allocator, но allocator/OS могут сохранить arenas.' },
    ],
    codeIntro:
      'Сценарий запускается отдельным CPython-процессом: dis, frame, цикл ссылок, GIL-конфигурация и сравнение блокировки asyncio с to_thread.',
    codeNotes: [
      'dis.get_instructions читает bytecode текущей версии без захардкоженных opcodes.',
      'sys._getframe показывает execution frame и является CPython-oriented API.',
      'weakref проверяет lifetime, не удерживая object сильной ссылкой.',
      'gc.collect запускается вручную только ради контролируемого опыта.',
      'create_task планирует coroutine; body получает управление после yield control loop.',
      'time.sleep блокирует thread; asyncio.to_thread выносит blocking call.',
    ],
    examples: [
      { title: 'Coroutine и Task', goal: 'Различить созданное вычисление и работу.', code: 'async def load_user(user_id: int):\n    return await repository.get(user_id)\n\ncoroutine = load_user(7)\ntask = asyncio.create_task(coroutine)\nuser = await task', notes: ['Потерянный coroutine ничего полезного не выполнит.', 'Task хранит result или exception.'] },
      { title: 'Параллельное ожидание I/O', goal: 'Не ждать независимые операции последовательно.', code: 'user, orders = await asyncio.gather(\n    load_user(user_id),\n    load_orders(user_id),\n)', notes: ['Concurrency не означает threads.', 'Errors и cancellation входят в контракт.'] },
      { title: 'Offload blocking I/O', goal: 'Не блокировать event-loop thread.', code: 'def read_legacy_file(path: str) -> bytes:\n    return legacy_client.read(path)\n\ndata = await asyncio.to_thread(read_legacy_file, path)', notes: ['to_thread не делает library intrinsically async.', 'Ограничивайте количество jobs.'] },
      { title: 'CPU в process pool', goal: 'Использовать несколько cores.', code: 'pool = ProcessPoolExecutor()\nresult = await asyncio.get_running_loop().run_in_executor(\n    pool, calculate_report, payload\n)', notes: ['Function и payload должны сериализоваться.', 'Pool должен быть долгоживущим и bounded.'] },
      { title: 'Диагностика bytecode', goal: 'Увидеть инструкции VM.', code: 'import dis\n\ndef total(values):\n    return sum(value * 2 for value in values)\n\ndis.dis(total)', notes: ['Opcode names зависят от версии.', 'Сначала используйте profiler.'] },
      { title: 'Наблюдение GC', goal: 'Измерять collector, а не гадать по RSS.', code: 'import gc\n\nbefore = gc.get_stats()\ncollected = gc.collect()\nafter = gc.get_stats()', notes: ['collect в request path не чинит leak.', 'Ищите удерживающие ссылки.'] },
    ],
    questions: [
      'Чем Python отличается от CPython?',
      'Когда async def начнёт выполнять body?',
      'Почему time.sleep задержит Tasks?',
      'Зачем reference counting дополняется cyclic GC?',
      'Почему GIL не отменяет Lock?',
      'Когда ProcessPool медленнее последовательного кода?',
    ],
  },
};
